# This is NOT the default gitleaks config. The default gitleaks config is located
# here: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
# This gitleaks config extends the default config and ignores secrets located in the `cmd/generate/config/rules`

title = "Gitleaks Extension Config"
[extend]
useDefault = true

[allowlist]
regexes = [
    '''xoxb-1234567890123-1234567890123-1234567890123-01234567890abcdefABCDEFG''',
]
