---
version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  default: all
  disable:
    - depguard
    - gochecknoglobals
    - exhaustruct
  settings:
    paralleltest:
      ignore-missing: true
      ignore-missing-subtests: true

  exclusions:
    generated: lax
    warn-unused: true
    # presets:
    #   - comments
    #   - common-false-positives
    #   - legacy
    #   - std-error-handling
    rules:
      - linters:
          - varnamelen
        text: is too short for the scope of its usage
      - linters:
          - forbidigo
        text: forbidden by pattern
      - linters:
          - revive
        text: should have comment or be unexported
      - linters:
          - lll
        text: characters long, which exceeds the maximum of
        path: "^.*_test\\.go$"
      - linters:
          - cyclop
        text: calculated cyclomatic complexity for function
        path: "^.*_test\\.go$"
      - linters:
          - funlen
        text: is too long
        path: "^.*_test\\.go$"
      - linters:
          - gocognit
        text: is high
        path: "^.*_test\\.go$"
      - linters:
          - maintidx
        path: "^.*_test\\.go$"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    # - golines
  exclusions:
    generated: lax
    # paths:
    #   - third_party$
    #   - builtin$
    #   - examples$
